<?php require './app/templates/header.phtml' ?>

<h4>Review</h4>

<ul class="list-group">
    <li class="list-group-item item-task">
        <div>
            <h5>Reseña</h5>
            <p>Pelicula: <a href="movies/<?= $review->id_movie ?>"><?= $review->title ?></a></p>
            <p>Calificacion: <?= $review->rating ?></p>
            <p><?= $review->body ?></p>
        </div>
    </li>
</ul>

<?php require './app/templates/footer.phtml' ?>