<form action="editMovie/<?= $movie->id_movie ?>" method="POST">

    <div class="row">
        <label for="title">Titulo</label>
        <input type="text" id="title" name="title" placeholder="Titulo" value="<?= $movie->title ?>" required>

        <label for="director">Director</label>
        <input type="text" id="director" name="director" placeholder="Director/es" value="<?= $movie->director ?>" required>

        <label for="release_date">Año de Estreno</label>
        <input type="number" id="release_date" name="release_date" placeholder="AÑO" value="<?= $movie->release_date ?>" required>

        <label for="runtime">Duracion</label>
        <input type="number" id="runtime" name="runtime" placeholder="en MINUTOS" value="<?= $movie->runtime ?>" required>

        <label for="genre">Genero</label>
        <input type="text" id="genre" name="genre" placeholder="Genero/s" value="<?= $movie->genre ?>" required>

        <label for="synopsis">Sinopsis</label>
        <textarea id="synopsis" name="synopsis" class="form-control" rows="4" cols="50" required><?= $movie->synopsis ?></textarea>

    </div>

    <button type="submit" class="btn btn-primary mt-2">Editar</button>
</form>