<form action="editReview/<?= $review->id_review ?>" method="POST">

    <div class="row">

        <label>Review a Editar</label>
        <label>De que pelicula es</label>
        <select required name="id_movie" class="form-control" value="<?= $review->id_movie ?>">
            <option selected disabled>Seleccione la pelicula</option>
            <?php foreach ($movies as $movie) : ?>
                <option value="<?= $movie->id_movie ?>"><?= $movie->title ?></option>
            <?php endforeach ?>
        </select>

        <label>Calificacion</label>
        <input required name="rating" type="number" placeholder="Ingrese la calificacion" class="form-control" value="<?= $review->rating ?>">

        <label>Cuerpo de la reseña</label>
        <textarea rows="4" cols="50" required name="body" type="text" placeholder="Ingrese reseña" class="form-control" ><?= $review->body ?></textarea>
    </div>

    <button type="submit" class="btn btn-primary mt-2">Editar</button>
</form>