<form action="addMovie" method="POST">

    <div class="row">
        <label for="title">Titulo</label>
        <input type="text" id="title" name="title" placeholder="Titulo" required>

        <label for="director">Director</label>
        <input type="text" id="director" name="director" placeholder="Director/es" required>

        <label for="release_date">Año de Estreno</label>
        <input type="number" id="release_date" name="release_date" placeholder="AÑO" required>

        <label for="runtime">Duracion</label>
        <input type="number" id="runtime" name="runtime" placeholder="en MINUTOS" required>

        <label for="genre">Genero</label>
        <input type="text" id="genre" name="genre" placeholder="Genero/s" required>

        <label for="synopsis">Sinopsis</label>
        <textarea id="synopsis" name="synopsis" placeholder="Ingrese la sinopsis" class="form-control" rows="4" cols="50" required></textarea>

    </div>

    <button type="submit" class="btn btn-primary mt-2">Agregar</button>
</form>